In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
a

array([-0.34980907,  0.96412955, -0.20821984,  1.47587656,  0.56444975])

In [3]:
a.shape #nither row vector nor column vector

(5,)

In [4]:
print(a.T)#a and aT(transpose) look the same

[-0.34980907  0.96412955 -0.20821984  1.47587656  0.56444975]


In [5]:
a.T.shape

(5,)

In [6]:
np.dot(a,a.T) #gives  out a number

3.5920828214282357

In [7]:
b = np.random.rand(5,1) #commits as a 5*1 column vector
b

array([[0.27974447],
       [0.96858128],
       [0.83742114],
       [0.55065839],
       [0.40447289]])

In [8]:
b.T

array([[0.27974447, 0.96858128, 0.83742114, 0.55065839, 0.40447289]])

In [9]:
np.dot(b,b.T)

array([[0.07825697, 0.27095525, 0.23426393, 0.15404364, 0.11314905],
       [0.27095525, 0.93814969, 0.81111044, 0.53335741, 0.39176487],
       [0.23426393, 0.81111044, 0.70127416, 0.46113298, 0.33871415],
       [0.15404364, 0.53335741, 0.46113298, 0.30322466, 0.22272639],
       [0.11314905, 0.39176487, 0.33871415, 0.22272639, 0.16359832]])

In [10]:
np.array([[[1],[2]],[[3],[4]]])

array([[[1],
        [2]],

       [[3],
        [4]]])

In [11]:
an = np.random.randn(1228,150)
ab = np.random.randn(150,45)

In [12]:
np.dot(an,ab).shape

(1228, 45)

In [13]:
np.dot(an,ab)

array([[  3.91432859,  -9.78496143,  -1.05313405, ...,  -9.34065587,
        -13.80918656,   4.63293496],
       [ -7.9772719 , -15.07351063, -10.0995431 , ...,  12.87766546,
          8.3617837 ,   2.59783472],
       [-13.56563497,  17.18224275, -23.57579578, ...,  10.16891954,
         -2.61052014,   1.8912476 ],
       ...,
       [ -7.29832357,  24.38483096,  26.85439665, ...,  -3.21108625,
         -5.57725755,  25.13161492],
       [ 17.34458857,   8.66067028,  -1.07282769, ...,  -4.93449501,
         -3.28673625,   5.93433378],
       [ 17.08577082,   0.19349536,  19.23911473, ...,  -0.13587844,
        -16.09241762, -21.00454198]])

In [18]:
a = np.random.rand(2,3)
np.sum(a, axis=1, keepdims= True).shape, np.sum(a, axis=0, keepdims= True).shape

((2, 1), (1, 3))